# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'translate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_translate(object):
    def setupUi(self, translate):
        translate.setObjectName("translate")
        translate.resize(653, 650)
        self.centralwidget = QtWidgets.QWidget(translate)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.output = QtWidgets.QTextEdit(self.centralwidget)
        self.output.setObjectName("output")
        self.gridLayout.addWidget(self.output, 2, 0, 1, 2)
        translate.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(translate)
        self.statusbar.setObjectName("statusbar")
        translate.setStatusBar(self.statusbar)
        

        self.retranslateUi(translate)
        QtCore.QMetaObject.connectSlotsByName(translate)

    def retranslateUi(self, translate):
        _translate = QtCore.QCoreApplication.translate
        translate.setWindowTitle(_translate("translate", "MainWindow"))
        self.pushButton.setText(_translate("translate", "translate"))
        self.pushButton.setShortcut(_translate("translate", "Return"))
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow
import translate
from functools import partial
import requests


def convert(ui):
    url="https://fanyi.baidu.com/sug"
    input = ui.lineEdit.text()
    dat={
        "kw":input
    }
    response = requests.post(url,data=dat)
    s=""
    for i in response.json()['data']:
        s+=str(i)
    ui.output.setText(s)
if __name__ == '__main__':
    font = QtGui.QFont()
    font.setPointSize(12)  # 括号里的数字可以设置成自己想要的字体大小
    font.setFamily("SimHei")  # 黑体
    app = QApplication(sys.argv)
    app.setFont(font)
    MainWindow = QMainWindow()
    ui = translate.Ui_translate()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.pushButton.clicked.connect(partial(convert, ui))
    sys.exit(app.exec_())